FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json .npmrc ./
RUN npm ci

COPY tsconfig.json vite.config.ts ./
COPY src ./src
COPY static ./static
RUN npm run prepare
COPY docker/auth-entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 5003
ENTRYPOINT ["/entrypoint.sh"]
