server {
    listen 80;

    location / {
        proxy_pass http://zitadel-api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host localhost;
        proxy_set_header X-Forwarded-Proto http;
    }
}
